#!/usr/bin/env ruby

require_relative "generator"

override = ARGV[0] == "--override"

connectors = JSON.parse(File.read("./generator/connectors.json"))
connectors.each do |schema_name, connector|
  Generator.new(
    connector["name"],
    connector["schema_name"],
    connector["overview"]["description"],
    connector["body"]["description"],
    connector["bullets_for_metrics"],
    connector["bullets_for_reasons"],
  ).generate(override)
  print "."
end

puts "\nDone!"
